apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finalapp
  ingress
  namespace: kalin-final
spec:
  rules:
  - host: kfinalapp.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finalappsvc
            port:
              number: 80