name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
       
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: log into docker
        uses: docker/Login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: build and image
        run: |
          docker build \
          -t kalinatsnow/inventorymanagement:${{github.run_number}} \
          -t kalinatsnow/inventorymanagement:latest \
          .

          docker push kalinatsnow/inventorymanagement --all-tags

      - name: kube deploy
        run : |
          export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin

          export IMAGE_TAG=${{ github.run_number }}

          for file in kube/*; do
              echo "Applying $file"
              cat "$file" | envsubst | kubectl apply -f -;
          done